### ISSUE TITLE
unnecessary line?

### ISSUE THREAD

**Issue by norayr** [jpbarraca/mail-trends#6]
I am connecting to not gmail server, and having this error.
```
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    message_infos = GetMessageInfos(opts)
  File "main.py", line 104, in GetMessageInfos
    for mailbox in m.GetMailboxes():
  File "/home/nil/hey/mail-trends/mail.py", line 61, in GetMailboxes
    mailboxes.remove('[Gmail]')
```

It goes away if I comment line 61 in mail.py module.

**Comment by jpbarraca** [comment]
What is the actual error that you are having?
That only shows the stack trace
